### ISSUE TITLE
Add documentation to hoomd/state.py

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#711]
## Purpose

This file needs to have better documentation of its class `State` for public facing properties, and methods. In addition, its docstring needs to be elaborated.

## Tasks

- [ ] Expand docstring for `hoomd.State`.
- [ ] Add docstrings for pubilic (not leading with an underscore) methods and properties of `hoomd.State`, or after discussion explicitly mark code with the appropriate error code.
- [ ] Make sure docstrings are correct Google style using pydocstyle.
- [ ] Add file to CI pydocstyle checking.
- [ ] Make sure documentation builds without warnings.

For help in completing these steps, see the information below.

## Pertinent Information

* [Docstring formatting](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html) - how to correctly format class and function docstrings.
* Private classes and functions - in Python anything with a leading underscore (with few execptions) can be considered _private_ or not to be changed or called by an user. Users can access them, but code behavior after doing so is not guaranteed.
* Information about how the class works can be found in the new HOOMD-blue tutorial [here](https://github.com/glotzerlab/hoomd-examples/pull/12). This should provide some idea about how the class in question and many of its methods work.
* To mark a method or class as undocumented use the `# noqa` marker with the correct error code.
````python
def foo(bar):  # noqa: D103
    pass

class Baz:  # noqa: D101
    def egg(self):  # noqa: D102
        pass
````
* A complete list of error codes for docstrings can be seen in pydocstyle's documentation [here](http://www.pydocstyle.org/en/5.0.1/error_codes.html). Helpful information on its usage can be found [here](http://www.pydocstyle.org/en/5.0.1/usage.html).
* To build documentation you need at least Python 3.7 (requirement for a sphinx feature we use). sphinx and the read the docs theme must also be installed `python3 -m pip install sphinx sphinx-rtd-theme`.
* To build the documentation from the project root directory use `python3 -m sphinx ./sphinx-doc ./docs -n -W --keep-going`.
* To view built documentation in a browser type in the address bar `file:///path/to/hoomd/root/docs/index.html`
