### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#716]
## Purpose

Removing these files will clear up the namespace and remove old code (plus negative LoC PR's are awesome).

## Tasks

- [ ] Remove files:
  * context.py
  * group.py
  * lattice.py
  * init.py
  * hdf5.py
  * option.py
  * meta.py
- [ ] Remove any references to modules (including in documentation)
- [ ] Ensure tests and builds still pass

## Pertinent Information

* CMakeLists.txt will have to be changed for builds to pass
* grep or a similar program or a IDE will be helpful to find all references. Finding references in the documentation is important too.

**Comment by mikemhenry** [comment]
Remove files:
- [ ] context.py
- [ ] group.py
- [ ] lattice.py
- [ ] init.py
- [ ] hdf5.py
- [ ] option.py
- [ ] meta.py

**Comment by mikemhenry** [comment]
Note: I skipped over these files as they will need a complete rewrite:
- [ ] `restartable-jobs.rst`
