### ISSUE TITLE
Make hoomd.device.auto a function rather than class

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#717]
## Purpose

Given there are CPU and GPU device classes, `hoomd.device.Auto` should be a function `hoomd.device.auto` that returns either a CPU or GPU object. 

## Tasks

- [ ] Remove `hoomd.device.Auto`
- [ ] Write function `hoomd.device.auto`
- [ ] Document and test function

## Pertinent Information

Since we default to GPU, we could just try to create a GPU device object and if it fails return a CPU device in Python.

**Comment by joaander** [comment]
The C++ `ExecutionConfiguration` class implements the auto-selection logic. The new `auto` function can construct this object and then return a constructed `CPU` or `GPU` object based on which mode `ExecutionConfiguration` chooses.
